version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root@123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
